defaultName: ${DW_DEFAULT_NAME:-IoT}

server:
  applicationConnectors:
    - type: http
      port: 18080
    - type: https
      port: 18081
      keyStorePath: C:\BIX\development\tradeio\com.bix.kyc\bixdocslocal.jks
      keyStorePassword: 123456
      keyStoreType: JKS
      validateCerts: false
      validatePeers: false
  adminConnectors:
    - type: http
      port: 18082


  
# Logging settings.
logging:
  level: INFO
  loggers:
    edu.seecs.dropwizard: INFO

    # Redirects SQL logs to a separate file
    org.hibernate.SQL:
      level: INFO
  appenders:    
    - type: console
    - type: file
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: ./log/application.log
      archivedLogFilenamePattern: ./log/application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MB

viewRendererConfiguration:
    .ftl:
        strict_syntax: yes
        whitespace_stripping: yes

swagger:
  resourcePackage: edu.seecs.dropwizard
  
